redis_ambassador:
    container_name: redis_ambassador
    image: svendowideit/ambassador
    expose:
        - "6379"
    environment:
        - REDIS_PORT_6379_TCP=tcp://192.241.254.231:6379

redis_client:
    container_name: redis_client
    image: relateiq/redis-cli
    links:
        - redis_ambassador:redis
